# 查询
extend type query {
  # appUser 总行数
  appUserCount(param: QueryListParam): Int
  # appUser 分页查询
  appUserList(param: QueryListParam): AppUserList
  # appUser  id 获取
  appUser(id: ID!): AppUser
  # appUser 有条件返回
  appUserAll(param: QueryListParam): [AppUser]
}

# 操作
extend type mutation {
  # appUser 新增 or 修改
  appUser(param: AppUserSaveIn!): AppUser
  # appUser 批量 新增 or 修改
  appUserBulk(param: [AppUserSaveIn]!): [AppUser]
  # appUser 根据id删除
  appUserDestroy(id: ID!): String
}
